#!/usr/bin/env python3
"""Create production env files with generated secrets.

The script writes credentials to local files and intentionally avoids printing
secret values to stdout. Keep the generated files out of git.
"""
from __future__ import annotations

import argparse
import base64
import os
import secrets
import shutil
from datetime import datetime, timezone
from pathlib import Path


ROOT_ENV = Path(".env")
BACKEND_ENV = Path("backend/.env")
CREDENTIALS_FILE = Path("ROUTER_CREDENTIALS.txt")


def _fernet_key() -> str:
    try:
        from cryptography.fernet import Fernet

        return Fernet.generate_key().decode("ascii")
    except Exception:
        return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def _token_urlsafe() -> str:
    return secrets.token_urlsafe(32)


def _backup(path: Path) -> Path | None:
    if not path.exists():
        return None
    suffix = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    backup = path.with_name(f"{path.name}.bak.{suffix}")
    shutil.copy2(path, backup)
    return backup


def _write_private(path: Path, content: str, *, force: bool) -> Path | None:
    if path.exists() and not force:
        raise SystemExit(f"{path} already exists. Re-run with --force to rotate and back it up.")
    backup = _backup(path) if force else None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(0o600)
    return backup


def _normalize_base_path(value: str, *, trailing_slash: bool) -> str:
    if not value:
        return "/"
    normalized = "/" + value.strip("/")
    return normalized + "/" if trailing_slash else normalized


def build_files(args: argparse.Namespace) -> tuple[str, str, str]:
    mysql_root_password = _token_urlsafe()
    mysql_password = _token_urlsafe()
    jwt_secret_key = _token_urlsafe()
    router_api_key = f"goku-router-{_token_urlsafe()}"
    admin_password = _token_urlsafe()
    router_secret_key = _fernet_key()

    frontend_base = _normalize_base_path(args.frontend_base_path, trailing_slash=True)
    frontend_basename = _normalize_base_path(args.frontend_base_path, trailing_slash=False)
    api_base = _normalize_base_path(args.api_base_path, trailing_slash=False)

    root_env = f"""# Generated by scripts/prepare_prod_env.py. Do not commit.
ROUTER_BIND_HOST=127.0.0.1
ROUTER_API_PORT={args.api_port}
ROUTER_ADMIN_PORT={args.admin_port}
MYSQL_ROOT_PASSWORD={mysql_root_password}
MYSQL_DATABASE=goku_router
MYSQL_USER=goku_router
MYSQL_PASSWORD={mysql_password}
VITE_BACKEND_URL={api_base}
VITE_FRONTEND_BASE={frontend_base}
VITE_FRONTEND_BASENAME={frontend_basename}
"""

    database_url = f"mysql+pymysql://goku_router:{mysql_password}@mysql:3306/goku_router"
    backend_env = f"""# Generated by scripts/prepare_prod_env.py. Do not commit.
APP_ENV=production
DATABASE_URL={database_url}
ROUTER_API_KEYS={router_api_key}
ALLOWED_ORIGINS={args.allowed_origin}
JWT_SECRET_KEY={jwt_secret_key}
JWT_EXPIRE_MINUTES=1440
ADMIN_USER={args.admin_user}
ADMIN_PASSWORD={admin_password}
ROUTER_SECRET_KEY={router_secret_key}
"""

    credentials = f"""Goku-Router production credentials
Generated: {datetime.now(timezone.utc).isoformat()}

Admin URL: {args.public_admin_url}
Admin user: {args.admin_user}
Admin password: {admin_password}

Router API key: {router_api_key}
MySQL user: goku_router
MySQL password: {mysql_password}
MySQL root password: {mysql_root_password}

Keep this file offline or in your password manager. Do not commit it.
"""
    return root_env, backend_env, credentials


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate production env files for Goku-Router.")
    parser.add_argument("--allowed-origin", required=True, help="Browser origin for the admin UI, e.g. https://aipass.example.com")
    parser.add_argument("--public-admin-url", default="https://aipass.example.com/router/", help="Operator-facing admin URL")
    parser.add_argument("--api-base-path", default="/router-api", help="Frontend API base path when proxied")
    parser.add_argument("--frontend-base-path", default="/router", help="Frontend public base path when proxied")
    parser.add_argument("--api-port", default="8159")
    parser.add_argument("--admin-port", default="5159")
    parser.add_argument("--admin-user", default="admin")
    parser.add_argument("--force", action="store_true", help="Rotate existing files after writing timestamped backups")
    args = parser.parse_args()

    root_env, backend_env, credentials = build_files(args)
    backups = [
        backup
        for backup in [
            _write_private(ROOT_ENV, root_env, force=args.force),
            _write_private(BACKEND_ENV, backend_env, force=args.force),
            _write_private(CREDENTIALS_FILE, credentials, force=args.force),
        ]
        if backup is not None
    ]

    print("Generated production env files without printing secret values.")
    print(f"root_env={ROOT_ENV}")
    print(f"backend_env={BACKEND_ENV}")
    print(f"credentials={CREDENTIALS_FILE}")
    if backups:
        print("backups=" + ",".join(str(path) for path in backups))
    print("Next: docker compose -f docker-compose.prod.yml up -d --build")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
